version: '3.1'

services:
  graph_db:
    image: neo4j:4.4.28-community
    environment:
        NEO4J_AUTH: 'neo4j/letmein'
        NEO4JLABS_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - graph_db:/data
      - ./example_data:/var/lib/neo4j/import/example_data

volumes:
  graph_db:
    driver: local
